#I need to import a task nodejs.yaml in catalogue

- name: Install NodeJs
  ansible.builtin.import_role:
      name: common
      tasks_from: nodejs

- name: Set-up app(user & directory)
  ansible.builtin.import_role:
      name: common
      tasks_from: app-setup


- name: Install the dependencies.
  ansible.builtin.command: npm install 
  args:
    chdir: /app

- name: Set-up service
  ansible.builtin.import_role:
      name: common
      tasks_from: systemd-setup-service

- name: setup MongoDB
  ansible.builtin.import_role:
      name: common
      tasks_from: load-mongo-schema


